# =============================================
# NEON PostgreSQL - Producción
# =============================================
spring.datasource.url=jdbc:postgresql://ep-aged-cherry-akisg9jr-pooler.c-3.us-west-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_S5rM0cHfahnv
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA - 'update' crea las tablas la 1era vez y las mantiene en reinicios
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Deshabilitar consola H2 en producción
spring.h2.console.enabled=false

# Puerto (cambia a 8081 si 8080 está ocupado)
server.port=8081

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=housesrural@gmail.com
spring.mail.password=owwq eynp zcjr laog
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

