spring.application.name=rural-houses
spring.profiles.active=dev
#mvn spring-boot:run "-Dspring-boot.run.profiles=prod"

app.jwt.secret=MySuperSecretKeyForJwtToken12345678901234567890
app.jwt.expiration=86400000

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080
